# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman

# Include any dependencies generated for this target.
include CMakeFiles/Hangman.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/Hangman.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/Hangman.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/Hangman.dir/flags.make

CMakeFiles/Hangman.dir/src/Box.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Box.cpp.o: src/Box.cpp
CMakeFiles/Hangman.dir/src/Box.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/Hangman.dir/src/Box.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Box.cpp.o -MF CMakeFiles/Hangman.dir/src/Box.cpp.o.d -o CMakeFiles/Hangman.dir/src/Box.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Box.cpp

CMakeFiles/Hangman.dir/src/Box.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Box.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Box.cpp > CMakeFiles/Hangman.dir/src/Box.cpp.i

CMakeFiles/Hangman.dir/src/Box.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Box.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Box.cpp -o CMakeFiles/Hangman.dir/src/Box.cpp.s

CMakeFiles/Hangman.dir/src/Buttons.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Buttons.cpp.o: src/Buttons.cpp
CMakeFiles/Hangman.dir/src/Buttons.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/Hangman.dir/src/Buttons.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Buttons.cpp.o -MF CMakeFiles/Hangman.dir/src/Buttons.cpp.o.d -o CMakeFiles/Hangman.dir/src/Buttons.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Buttons.cpp

CMakeFiles/Hangman.dir/src/Buttons.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Buttons.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Buttons.cpp > CMakeFiles/Hangman.dir/src/Buttons.cpp.i

CMakeFiles/Hangman.dir/src/Buttons.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Buttons.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Buttons.cpp -o CMakeFiles/Hangman.dir/src/Buttons.cpp.s

CMakeFiles/Hangman.dir/src/Colors.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Colors.cpp.o: src/Colors.cpp
CMakeFiles/Hangman.dir/src/Colors.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/Hangman.dir/src/Colors.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Colors.cpp.o -MF CMakeFiles/Hangman.dir/src/Colors.cpp.o.d -o CMakeFiles/Hangman.dir/src/Colors.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Colors.cpp

CMakeFiles/Hangman.dir/src/Colors.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Colors.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Colors.cpp > CMakeFiles/Hangman.dir/src/Colors.cpp.i

CMakeFiles/Hangman.dir/src/Colors.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Colors.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Colors.cpp -o CMakeFiles/Hangman.dir/src/Colors.cpp.s

CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o: src/DifficultyScreen.cpp
CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o -MF CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o.d -o CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/DifficultyScreen.cpp

CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/DifficultyScreen.cpp > CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.i

CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/DifficultyScreen.cpp -o CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.s

CMakeFiles/Hangman.dir/src/Display.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Display.cpp.o: src/Display.cpp
CMakeFiles/Hangman.dir/src/Display.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/Hangman.dir/src/Display.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Display.cpp.o -MF CMakeFiles/Hangman.dir/src/Display.cpp.o.d -o CMakeFiles/Hangman.dir/src/Display.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Display.cpp

CMakeFiles/Hangman.dir/src/Display.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Display.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Display.cpp > CMakeFiles/Hangman.dir/src/Display.cpp.i

CMakeFiles/Hangman.dir/src/Display.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Display.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Display.cpp -o CMakeFiles/Hangman.dir/src/Display.cpp.s

CMakeFiles/Hangman.dir/src/Errors.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Errors.cpp.o: src/Errors.cpp
CMakeFiles/Hangman.dir/src/Errors.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/Hangman.dir/src/Errors.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Errors.cpp.o -MF CMakeFiles/Hangman.dir/src/Errors.cpp.o.d -o CMakeFiles/Hangman.dir/src/Errors.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Errors.cpp

CMakeFiles/Hangman.dir/src/Errors.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Errors.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Errors.cpp > CMakeFiles/Hangman.dir/src/Errors.cpp.i

CMakeFiles/Hangman.dir/src/Errors.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Errors.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Errors.cpp -o CMakeFiles/Hangman.dir/src/Errors.cpp.s

CMakeFiles/Hangman.dir/src/Event.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Event.cpp.o: src/Event.cpp
CMakeFiles/Hangman.dir/src/Event.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/Hangman.dir/src/Event.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Event.cpp.o -MF CMakeFiles/Hangman.dir/src/Event.cpp.o.d -o CMakeFiles/Hangman.dir/src/Event.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Event.cpp

CMakeFiles/Hangman.dir/src/Event.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Event.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Event.cpp > CMakeFiles/Hangman.dir/src/Event.cpp.i

CMakeFiles/Hangman.dir/src/Event.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Event.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Event.cpp -o CMakeFiles/Hangman.dir/src/Event.cpp.s

CMakeFiles/Hangman.dir/src/File.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/File.cpp.o: src/File.cpp
CMakeFiles/Hangman.dir/src/File.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/Hangman.dir/src/File.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/File.cpp.o -MF CMakeFiles/Hangman.dir/src/File.cpp.o.d -o CMakeFiles/Hangman.dir/src/File.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/File.cpp

CMakeFiles/Hangman.dir/src/File.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/File.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/File.cpp > CMakeFiles/Hangman.dir/src/File.cpp.i

CMakeFiles/Hangman.dir/src/File.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/File.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/File.cpp -o CMakeFiles/Hangman.dir/src/File.cpp.s

CMakeFiles/Hangman.dir/src/Fonts.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Fonts.cpp.o: src/Fonts.cpp
CMakeFiles/Hangman.dir/src/Fonts.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object CMakeFiles/Hangman.dir/src/Fonts.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Fonts.cpp.o -MF CMakeFiles/Hangman.dir/src/Fonts.cpp.o.d -o CMakeFiles/Hangman.dir/src/Fonts.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Fonts.cpp

CMakeFiles/Hangman.dir/src/Fonts.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Fonts.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Fonts.cpp > CMakeFiles/Hangman.dir/src/Fonts.cpp.i

CMakeFiles/Hangman.dir/src/Fonts.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Fonts.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Fonts.cpp -o CMakeFiles/Hangman.dir/src/Fonts.cpp.s

CMakeFiles/Hangman.dir/src/GameScreen.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/GameScreen.cpp.o: src/GameScreen.cpp
CMakeFiles/Hangman.dir/src/GameScreen.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object CMakeFiles/Hangman.dir/src/GameScreen.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/GameScreen.cpp.o -MF CMakeFiles/Hangman.dir/src/GameScreen.cpp.o.d -o CMakeFiles/Hangman.dir/src/GameScreen.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/GameScreen.cpp

CMakeFiles/Hangman.dir/src/GameScreen.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/GameScreen.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/GameScreen.cpp > CMakeFiles/Hangman.dir/src/GameScreen.cpp.i

CMakeFiles/Hangman.dir/src/GameScreen.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/GameScreen.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/GameScreen.cpp -o CMakeFiles/Hangman.dir/src/GameScreen.cpp.s

CMakeFiles/Hangman.dir/src/Health.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Health.cpp.o: src/Health.cpp
CMakeFiles/Hangman.dir/src/Health.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building CXX object CMakeFiles/Hangman.dir/src/Health.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Health.cpp.o -MF CMakeFiles/Hangman.dir/src/Health.cpp.o.d -o CMakeFiles/Hangman.dir/src/Health.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Health.cpp

CMakeFiles/Hangman.dir/src/Health.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Health.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Health.cpp > CMakeFiles/Hangman.dir/src/Health.cpp.i

CMakeFiles/Hangman.dir/src/Health.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Health.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Health.cpp -o CMakeFiles/Hangman.dir/src/Health.cpp.s

CMakeFiles/Hangman.dir/src/Initialize.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Initialize.cpp.o: src/Initialize.cpp
CMakeFiles/Hangman.dir/src/Initialize.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building CXX object CMakeFiles/Hangman.dir/src/Initialize.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Initialize.cpp.o -MF CMakeFiles/Hangman.dir/src/Initialize.cpp.o.d -o CMakeFiles/Hangman.dir/src/Initialize.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Initialize.cpp

CMakeFiles/Hangman.dir/src/Initialize.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Initialize.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Initialize.cpp > CMakeFiles/Hangman.dir/src/Initialize.cpp.i

CMakeFiles/Hangman.dir/src/Initialize.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Initialize.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Initialize.cpp -o CMakeFiles/Hangman.dir/src/Initialize.cpp.s

CMakeFiles/Hangman.dir/src/Logic.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Logic.cpp.o: src/Logic.cpp
CMakeFiles/Hangman.dir/src/Logic.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building CXX object CMakeFiles/Hangman.dir/src/Logic.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Logic.cpp.o -MF CMakeFiles/Hangman.dir/src/Logic.cpp.o.d -o CMakeFiles/Hangman.dir/src/Logic.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Logic.cpp

CMakeFiles/Hangman.dir/src/Logic.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Logic.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Logic.cpp > CMakeFiles/Hangman.dir/src/Logic.cpp.i

CMakeFiles/Hangman.dir/src/Logic.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Logic.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Logic.cpp -o CMakeFiles/Hangman.dir/src/Logic.cpp.s

CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o: src/RetryScreen.cpp
CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building CXX object CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o -MF CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o.d -o CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/RetryScreen.cpp

CMakeFiles/Hangman.dir/src/RetryScreen.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/RetryScreen.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/RetryScreen.cpp > CMakeFiles/Hangman.dir/src/RetryScreen.cpp.i

CMakeFiles/Hangman.dir/src/RetryScreen.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/RetryScreen.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/RetryScreen.cpp -o CMakeFiles/Hangman.dir/src/RetryScreen.cpp.s

CMakeFiles/Hangman.dir/src/Screen.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Screen.cpp.o: src/Screen.cpp
CMakeFiles/Hangman.dir/src/Screen.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building CXX object CMakeFiles/Hangman.dir/src/Screen.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Screen.cpp.o -MF CMakeFiles/Hangman.dir/src/Screen.cpp.o.d -o CMakeFiles/Hangman.dir/src/Screen.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Screen.cpp

CMakeFiles/Hangman.dir/src/Screen.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Screen.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Screen.cpp > CMakeFiles/Hangman.dir/src/Screen.cpp.i

CMakeFiles/Hangman.dir/src/Screen.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Screen.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Screen.cpp -o CMakeFiles/Hangman.dir/src/Screen.cpp.s

CMakeFiles/Hangman.dir/src/Start.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Start.cpp.o: src/Start.cpp
CMakeFiles/Hangman.dir/src/Start.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Building CXX object CMakeFiles/Hangman.dir/src/Start.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Start.cpp.o -MF CMakeFiles/Hangman.dir/src/Start.cpp.o.d -o CMakeFiles/Hangman.dir/src/Start.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Start.cpp

CMakeFiles/Hangman.dir/src/Start.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Start.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Start.cpp > CMakeFiles/Hangman.dir/src/Start.cpp.i

CMakeFiles/Hangman.dir/src/Start.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Start.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Start.cpp -o CMakeFiles/Hangman.dir/src/Start.cpp.s

CMakeFiles/Hangman.dir/src/StartScreen.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/StartScreen.cpp.o: src/StartScreen.cpp
CMakeFiles/Hangman.dir/src/StartScreen.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_17) "Building CXX object CMakeFiles/Hangman.dir/src/StartScreen.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/StartScreen.cpp.o -MF CMakeFiles/Hangman.dir/src/StartScreen.cpp.o.d -o CMakeFiles/Hangman.dir/src/StartScreen.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/StartScreen.cpp

CMakeFiles/Hangman.dir/src/StartScreen.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/StartScreen.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/StartScreen.cpp > CMakeFiles/Hangman.dir/src/StartScreen.cpp.i

CMakeFiles/Hangman.dir/src/StartScreen.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/StartScreen.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/StartScreen.cpp -o CMakeFiles/Hangman.dir/src/StartScreen.cpp.s

CMakeFiles/Hangman.dir/src/Text.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Text.cpp.o: src/Text.cpp
CMakeFiles/Hangman.dir/src/Text.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_18) "Building CXX object CMakeFiles/Hangman.dir/src/Text.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Text.cpp.o -MF CMakeFiles/Hangman.dir/src/Text.cpp.o.d -o CMakeFiles/Hangman.dir/src/Text.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Text.cpp

CMakeFiles/Hangman.dir/src/Text.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Text.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Text.cpp > CMakeFiles/Hangman.dir/src/Text.cpp.i

CMakeFiles/Hangman.dir/src/Text.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Text.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Text.cpp -o CMakeFiles/Hangman.dir/src/Text.cpp.s

CMakeFiles/Hangman.dir/src/Word.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/Word.cpp.o: src/Word.cpp
CMakeFiles/Hangman.dir/src/Word.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_19) "Building CXX object CMakeFiles/Hangman.dir/src/Word.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/Word.cpp.o -MF CMakeFiles/Hangman.dir/src/Word.cpp.o.d -o CMakeFiles/Hangman.dir/src/Word.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Word.cpp

CMakeFiles/Hangman.dir/src/Word.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/Word.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Word.cpp > CMakeFiles/Hangman.dir/src/Word.cpp.i

CMakeFiles/Hangman.dir/src/Word.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/Word.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/Word.cpp -o CMakeFiles/Hangman.dir/src/Word.cpp.s

CMakeFiles/Hangman.dir/src/main.cpp.o: CMakeFiles/Hangman.dir/flags.make
CMakeFiles/Hangman.dir/src/main.cpp.o: src/main.cpp
CMakeFiles/Hangman.dir/src/main.cpp.o: CMakeFiles/Hangman.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_20) "Building CXX object CMakeFiles/Hangman.dir/src/main.cpp.o"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Hangman.dir/src/main.cpp.o -MF CMakeFiles/Hangman.dir/src/main.cpp.o.d -o CMakeFiles/Hangman.dir/src/main.cpp.o -c /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/main.cpp

CMakeFiles/Hangman.dir/src/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Hangman.dir/src/main.cpp.i"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/main.cpp > CMakeFiles/Hangman.dir/src/main.cpp.i

CMakeFiles/Hangman.dir/src/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Hangman.dir/src/main.cpp.s"
	/data/user/0/ru.iiec.cxxdroid/files/bin/clang++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/src/main.cpp -o CMakeFiles/Hangman.dir/src/main.cpp.s

# Object files for target Hangman
Hangman_OBJECTS = \
"CMakeFiles/Hangman.dir/src/Box.cpp.o" \
"CMakeFiles/Hangman.dir/src/Buttons.cpp.o" \
"CMakeFiles/Hangman.dir/src/Colors.cpp.o" \
"CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o" \
"CMakeFiles/Hangman.dir/src/Display.cpp.o" \
"CMakeFiles/Hangman.dir/src/Errors.cpp.o" \
"CMakeFiles/Hangman.dir/src/Event.cpp.o" \
"CMakeFiles/Hangman.dir/src/File.cpp.o" \
"CMakeFiles/Hangman.dir/src/Fonts.cpp.o" \
"CMakeFiles/Hangman.dir/src/GameScreen.cpp.o" \
"CMakeFiles/Hangman.dir/src/Health.cpp.o" \
"CMakeFiles/Hangman.dir/src/Initialize.cpp.o" \
"CMakeFiles/Hangman.dir/src/Logic.cpp.o" \
"CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o" \
"CMakeFiles/Hangman.dir/src/Screen.cpp.o" \
"CMakeFiles/Hangman.dir/src/Start.cpp.o" \
"CMakeFiles/Hangman.dir/src/StartScreen.cpp.o" \
"CMakeFiles/Hangman.dir/src/Text.cpp.o" \
"CMakeFiles/Hangman.dir/src/Word.cpp.o" \
"CMakeFiles/Hangman.dir/src/main.cpp.o"

# External object files for target Hangman
Hangman_EXTERNAL_OBJECTS =

Hangman: CMakeFiles/Hangman.dir/src/Box.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Buttons.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Colors.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/DifficultyScreen.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Display.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Errors.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Event.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/File.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Fonts.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/GameScreen.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Health.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Initialize.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Logic.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/RetryScreen.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Screen.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Start.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/StartScreen.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Text.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/Word.cpp.o
Hangman: CMakeFiles/Hangman.dir/src/main.cpp.o
Hangman: CMakeFiles/Hangman.dir/build.make
Hangman: CMakeFiles/Hangman.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles --progress-num=$(CMAKE_PROGRESS_21) "Linking CXX executable Hangman"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/Hangman.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/Hangman.dir/build: Hangman
.PHONY : CMakeFiles/Hangman.dir/build

CMakeFiles/Hangman.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/Hangman.dir/cmake_clean.cmake
.PHONY : CMakeFiles/Hangman.dir/clean

CMakeFiles/Hangman.dir/depend:
	cd /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman /storage/emulated/0/Documents/Cxxdroid/cpp/Hangman/CMakeFiles/Hangman.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/Hangman.dir/depend

